### ISSUE TITLE
Finish README

### ISSUE THREAD

**Issue by micjamking** [micjamking/hello-world#1]
So that the humans git me.

**Comment by micjamking** [comment]
I'm having issues with the following CSS

```html
<header class="header"></header>
```

```css
.header {
  margin: 0 0 0 auto;
  padding: 20px;
}
```

```js
(function(){
  var body = document.getElementByTag('body');
})();
```
